### ISSUE TITLE
It can't seem to show up??

### ISSUE THREAD

**Issue by GrandWasTaken** [artginzburg/sudo-touchid#5]
I tried running `sudo say "Hello World"` and it would go to the enter password. Without showing any touchid.

**Comment by GrandWasTaken** [comment]
Nvm got it to work, seems like I must run sudo-touchid.

**Comment by artginzburg** [comment]
@GrandWasTaken oh, sorry for this. Maybe I should add something to Readme? Would be nice to have some feedback about the problem you experienced, even if it's a small one.

**Comment by GrandWasTaken** [comment]
Oh no need for any Readme. I just didn't read the instructions clearly.
